export const environment = {
  production: true,
  rootPath: window["rootPath"],
  rootPathApi: window["rootPathApi"],
  //formPath: '/DesktopModules/MVC/XOKA_SW_DNNModuleMyTask/Views/Item/assets/',
  username: window["_UserName"],
  phisicalPath: window["phisicalPath"],
  Lang_code: (window["lang"] as string).toLowerCase(),
  city: window["city"],
  appbase: window["_app_base"],
  location: window["locations"],
  numberOfpick: window["numberOfpick"],
  Lease_contract:window['Lease_contract'],
  con_report:window['con_report'],
  localGisServer: window["local_GIS_server"],
  rootPathnational:window['rootPathnational'],
  wfsGeoServer: window["wfs_geoserver"],
  PaymentReportPath: window["PaymentReportPath"],
  certReportPath: window["certReportPath"],
  LetterReportPath: window["LetterReportPath"],
  resourcePath: window["resourcePath"],
  overlayLayer: window["overlayLayer"],
  layerConfig: window["layerConfig"],
  iconpath: window["iconpath"],
  rootPath2: window["rootPath2"],
  formPath: window["formPath"],
  rootPath3: window["rootPath3"],
  groupLayerName: window["groupLayerName"],
  parentGroupName: window["parentGroupName"],
  SubcityName: window["SubcityName"],
  geoserverUrl: window["geoserverUrl"],
  geoserverUrlwfs: window["geoserverUrlwfs"],
  parentWorkspace: window["parentWorkspace"],
  geoser: window["geoser"],
  imagepathclock: window["_imagepathclock"],
  imagepathfile: window["_imagepathfile"],
  imagepathdeletefile: window["_imagepathdeletefile"],
  imagepathcheckmark: window["_imagepathcheckmark"],
  imagepathuploadfile: window["_imagepathuploadfile"],
  imagepath: window["_imagepath"],
  multipleplotcanbeadd: window["multipleplotcanbeadd"],
  propertytasks: window["propertytasks"],
  folderpath: window["folderpath"],
  Totalareatolerance: window["Totalareatolerance"],
  subcity: window["subcity"],
  rootpath2: window["rootpath2"],
  propertyvalidetion: window["propertyvalidetion"],
};
